#!/usr/bin/env bash

# Exit if any subcommand fails
set -e
set -o pipefail

source script/helpers/text_helpers

NEW_APP_NAME=$1

notice "Renaming 'src/method_overloading.cr'"
mv src/method_overloading.cr src/$NEW_APP_NAME.cr
print_done

notice "Installing node dependencies"
rg method_overloading -l | xargs sed -i "" "s/method_overloading/$NEW_APP_NAME/g"
print_done

notice "Committing changes to git"
git add .
git commit -m "Renaming application to $NEW_APP_NAME"
print_done
